name: Terraform Workflow

on:
  pull_request:
    branches:
      - main

jobs:
  plan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Terraform Init
        run: terraform init

      - name: Terraform Plan
        run: terraform plan
